bcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from clinic_app.views import *
from django.contrib.auth.models import User

from django_otp.admin import OTPAdminSite
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin


class OTPAdmin(OTPAdminSite):
    pass




admin_site = OTPAdmin(name='OTPAdmin')
admin_site.register(User)
admin_site.register(TOTPDevice,TOTPDeviceAdmin)


urlpatterns = [
    path('', include('core_app.urls' )),
    path('api/', include('website_app.urls' )),
    path('website/', include('website_app.urls' )),
    path('account/', include('account_app.urls' )),
    path('article/', include('article_app.urls' )),
    path('clinic/', include('clinic_app.urls' )),
    path('writer/', include('writers_app.urls' )),
    path('review/', include('review.urls' )),
    path('yt/', include('yt_app.urls' )),
    path('admin/', admin_site.urls),
    path('select2/', include("django_select2.urls")),
    path('create_patient/', PatientCreateView.as_view(), name='create_patient'),
    path("__debug__/", include("debug_toolbar.urls")),
    #path('select2/', include('select2.urls')),
]

website_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . views import *
from .  import views


app_name = 'website_app'


urlpatterns = [
    path('websites/', views.getAllWebsites, name='getAllWebsites'),
    path('websites/<str:id>', views.getWebsite, name='getWebsite'),
    path('websites/<str:id>/update/', views.updateWebsite, name='updateWebsite'),
    path('websites/create', views.newWebsite, name='newWebsite'),
    path('', WebsiteListView.as_view(), name='website_list'),
    path('create_website', WebsiteCreateView.as_view(), name='create_website'),
    path('<pk>/', WebsiteUpdateView.as_view(), name='website_detail'),
   
]

website_app/models.py
from django.db import models
from core_app.models import BaseModel
from django.urls import reverse
from auditlog.registry import auditlog


#
    
# Create your models here.
class AmazonAssociates(models.Model):

    AMAZONUSA = "USA"
    AMAZONINDIA = "IND"

    AMAZON_LOCATION_CHOICES = [
        (AMAZONUSA, "Amazon USA"),
        (AMAZONINDIA, "Amazon India"),
        
    ]
    
    amazon_associates_email = models.EmailField(max_length=100, null=True)
    amazon_tag = models.CharField(max_length=150, null=True)
    amazon_location = models.CharField(
        max_length=5,
        choices=AMAZON_LOCATION_CHOICES,
        default=AMAZONUSA,
    )


class DomainProviders(models.Model):
    provider_name = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.provider_name
    
class HostingProviders(models.Model):
    provider_name = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.provider_name

    

class Website(BaseModel):

    FREQUENCY_PUBLISHING = (
        ('OnceDaily', 'OnceDaily'),
        ('4/Week', '4/Week'),
    )
    website_name = models.CharField(max_length=50, null=True, blank=True)
    website_url = models.URLField(max_length=100, null=True, blank=True)
    admin_website = models.CharField(max_length=100, null=True, blank=True)
    admin_pass = models.CharField(max_length=100, null=True, blank=True)
    user_website = models.CharField(max_length=100, null=True, blank=True)
    user_pass = models.CharField(max_length=100, null=True, blank=True)
    email_website = models.EmailField(max_length=100, null=True, blank=True)
    email_pass = models.CharField(max_length=100, null=True, blank=True)
    amazon_email = models.ForeignKey(AmazonAssociates, on_delete=models.PROTECT, null=True, blank=True, related_name="associate_email")
    amazon_associates_tag = models.OneToOneField(AmazonAssociates, on_delete=models.PROTECT, null=True, blank=True, related_name="associate_tag")
   
    server =  models.URLField(max_length=100, null=True, blank=True)
    domain_provider = models.ForeignKey(DomainProviders, null=True, blank=True, on_delete=models.PROTECT) 
    hosting_provider = models.ForeignKey(HostingProviders, null=True, blank=True, on_delete=models.PROTECT) 
    publishing_frequency = models.CharField(max_length=20, choices=FREQUENCY_PUBLISHING, default='OnceDaily')
   
    def get_absolute_url(self):
        return reverse('website_app:website_detail', args=[str(self.id)])

    def __str__(self):
        return self.website_name







auditlog.register(Website)

website_app/forms.py
from django import forms
from .models import *


class createWebsiteForm(forms.ModelForm):

    class Meta:
        model = Website
        fields = '__all__'
        

        

        

website_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, UpdateView, CreateView
from . models import *
from.forms import *
from rest_framework.decorators import api_view
from .serializers import WebsiteSerializer
from rest_framework.response import Response

# Create your views here.




@api_view(['GET'])
def getAllWebsites(request):
    website = Website.objects.all()

    serializer = WebsiteSerializer(website, many=False)
    return Response(serializer.data)



@api_view(['GET'])
def getWebsite(request, id):
    website = Website.objects.filter(id=id)
    serializer = WebsiteSerializer(website, many=True)
    return Response(serializer.data)



@api_view(['POST'])
def newWebsite(request):
    
    data = request.data
    website = Website.objects.create(**data)
    serializer = WebsiteSerializer(website, many=False)
    return Response(serializer.data)


@api_view(['PUT'])
def updateWebsite(request, id):
    website = Website.objects.filter(id=id)

    website.website_name = request.data['website_name']

    website.save()

    serializer = WebsiteSerializer(website, many=True)
    return Response(serializer.data)


class WebsiteListView(ListView):
    model = Website
    template_name = "website_app/website_list.html"
    context_object_name = 'website'

    # def get_queryset(self, *args, **kwargs):
    #     # qs = super(WebsiteListView, self).get_queryset(*args, **kwargs)
    #     qs = {'all': qs.objects.all(),
    #           'active': qs.objects.filter(status='Active')
    #           }
              

        
    #     return qs



class WebsiteCreateView(CreateView):
    model = Website
    #fields = '__all__'
    form_class = createWebsiteForm
    template_name = 'website_app/create_website.html'

    
    
    
    def get_success_url(self):
        return self.object.get_absolute_url()
    


class WebsiteUpdateView(UpdateView):
    model = Website
    fields = '__all__'

    template_name = "website_app/website_detail.html"

    
   
   
    def get_success_url(self):
        return self.object.get_absolute_url()
    
    # def form_valid(self, form):
    #     messages.success(self.request, f'Save Completed ! Site has been updated')
    #     return super().form_valid(form)

website_app/templates/website_app/create_website.html
{% extends 'base_main.html' %}   {% load crispy_forms_tags %} 


{% block page_content %}
  
    <form action="" method="post" enctype="multipart/form-data">
    

      <div class="form-group">
        {% csrf_token %}

     

        {{form|crispy}}

        
    </div>
    <button  class="btn btn-primary">Update</button> 
      
    </form>

    

    <script>

var select_box_element = document.querySelector('id_domain_provider');

const config = {
    search: true, // Toggle search feature. Default: false
    creatable: false, // Creatable selection. Default: false
    clearable: false, // Clearable selection. Default: false
    maxHeight: '360px', // Max height for showing scrollbar. Default: 360px
    size: '', // Can be "sm" or "lg". Default ''
}
dselect(document.querySelector('#id_hosting_provider'), config)
    
  </script>
  
  {% endblock page_content %}

website_app/templates/website_app/website_detail.html
{% extends 'base_main.html' %}   {% load crispy_forms_tags %} 
{% block page_content %}
  
    <form action="" method="post" enctype="multipart/form-data">
    

      <div class="form-group">
        {% csrf_token %}

        {{form | crispy}}

        <!-- {{form.website_name|as_crispy_field}}
        {{form.website_url|as_crispy_field}}
        {{form.admin_website|as_crispy_field}}
        {{form.admin_pass|as_crispy_field}}
        {{form.email_website|as_crispy_field}} -->

        
    </div>
    <button  class="btn btn-primary">Update</button> 
      
    </form>



    <script>

      dselect(document.querySelector('#id_domain_provider') && document.querySelector('#id_hosting_provider'), {
  
          search: true
      });
  

    
  </script>
  
  {% endblock page_content %}

website_app/templates/website_app/website_list.html
{% extends 'base_main.html' %}   {% block page_content %}






<table id="data-table" class="table">
  <thead>
      <tr>
        <th scope="col">Website Name</th>
        <th scope="col">URL</th>
        <th scope="col">Admin</th>
        <th scope="col">User</th>
      </tr>
  </thead>
  <tbody>
    {% for w in website %}
      <tr>
        <tr>
          <th ><a href="{% url 'website_app:website_detail' w.id %}">{{w.website_name}}</a></th>
          <td colspan="2">{{w.website_url}}</td>
          <td>{{w.admin_website}}</td>
          <td>{{w.user_website}}</td>
          <td></td>
        </tr>

        {% endfor %}
      </tr>
  </tbody>
  <tfoot>
      <tr>
          <th>...</th>
      </tr>
  </tfoot>
</table>





{% endblock page_content %}